apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend
    env: aurtask
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    name: backend
    env: aurtask
