apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend
    env: aurtask
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
  selector:
    name: backend
    env: aurtask
