apiVersion: v1
kind: Pod
metadata:
    name: backend-pod
    labels:
      name: backend
      env: aurtask
spec:
   containers:
    - name: backend
      image: crazyfordevops/backend:vFinal
      ports:
        - containerPort: 8080
      env:
        - name: NAME
          value: "Zain"
